// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9fAhBvEapCd2_Fc48TjumFl-bwlphh50',
    appId: '1:516732021431:web:2addfa29661f8406fd7b32',
    messagingSenderId: '516732021431',
    projectId: 'attendence-d1f2d',
    authDomain: 'attendence-d1f2d.firebaseapp.com',
    storageBucket: 'attendence-d1f2d.appspot.com',
    measurementId: 'G-KSRWTY1T0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-SdRdcm5njP8l7-xY_2X7K8MWyWM9coM',
    appId: '1:516732021431:android:b7ce044b9fea176efd7b32',
    messagingSenderId: '516732021431',
    projectId: 'attendence-d1f2d',
    storageBucket: 'attendence-d1f2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqD5Y_oQEb0ui-DEKXuG98H3f9qin3F6Y',
    appId: '1:516732021431:ios:8221ff4345ada921fd7b32',
    messagingSenderId: '516732021431',
    projectId: 'attendence-d1f2d',
    storageBucket: 'attendence-d1f2d.appspot.com',
    iosBundleId: 'com.example.attendenceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqD5Y_oQEb0ui-DEKXuG98H3f9qin3F6Y',
    appId: '1:516732021431:ios:8221ff4345ada921fd7b32',
    messagingSenderId: '516732021431',
    projectId: 'attendence-d1f2d',
    storageBucket: 'attendence-d1f2d.appspot.com',
    iosBundleId: 'com.example.attendenceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9fAhBvEapCd2_Fc48TjumFl-bwlphh50',
    appId: '1:516732021431:web:ac4c6b5c981db05afd7b32',
    messagingSenderId: '516732021431',
    projectId: 'attendence-d1f2d',
    authDomain: 'attendence-d1f2d.firebaseapp.com',
    storageBucket: 'attendence-d1f2d.appspot.com',
    measurementId: 'G-C2LD680S2K',
  );

}